# Generated by Django 4.2.4 on 2023-08-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Meter Reading', 'Meter Reading'), ('Connection Setup', 'Connection Setup')], max_length=20)),
                ('details', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
